### ISSUE TITLE
PostgreSQL: PostgreSQL Tools Service component could not start.

### ISSUE THREAD

**Issue by HideyoshiNakazone** [microsoft/vscode-postgresql#83]
- PGSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Installing PostgreSQL
2. VS Code returns a error

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
>   File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
>   File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
>   File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
> ImportError: libffi.so.6: cannot open shared object file: No such file or directory
> [Error - 2:27:29 PM] Connection to server got closed. Server will not be restarted.

**Comment by AsterixMechant** [comment]
I am having this exact same issue, too. Here's some details about my running environment:

- Ubuntu 20.04 LTS
- Installed VS Code through Microsoft's official .deb file, not from snap or any other repo
- VS Code version 1.47.3
- PGSQL Extension version 0.3.0
- NodeJS version 12.18.3 LTS (installed from Node Version Manager - NVM)

I am not an expert or anything, but it seems to me that the problem is with the installed version of Python. The extension seems to rely on some package from Python 3.6, whereas Ubuntu 20.04 ships with Python 3.8. 

I wonder how this issue could be addressed for Focal Fossa users? Shoud we downgrade our Python version? I'm afraid this would break something on Ubuntu though. Can someone please point me on some good direction? 

Cheers!

**Comment by AsterixMechant** [comment]
So, I did some more digging, and here's what I've found:

- Python 3.6, which the extension depends on, uses a system library called libffi, more specifically, libffi6
- However, Ubuntu 20.04 ships with Python 3.8, and libffi7 instead
- Even after installing Python3.6, I stumbled upon the fact that I can't find libffi6 on apt repository 

So apparently, there's nothing one could do about this right now, but either switch back to Ubuntu 18.04 or sit back and hope that the dev team will upgrade the dependency on Python to version 3.8.

Or, alternatively - but I strongly recommend NOT doing so, even though it seems to work:

Follow the instructions in the accepted answer [on this discussion](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6), to symlink your libffi dependency to libffi7, tricking your Python runtime to think it is using the correct library version. However, it is hard to predict what kinds of other issues this could cause. I wouldn't really recommend doing so, so do it at your own risk!

**Comment by HideyoshiNakazone** [comment]
Technically i could just downgrade my Debian package of python because i mainly use Anaconda Python for my works. Thanks a lot for the response!

**Comment by chintanp** [comment]
[This](https://stackoverflow.com/a/63329830) solution of manually install `libffi.so.6` worked for me on Ubuntu 20.04. It is hacky (as it is not suggested to manually install packages in Ubuntu), it seems the least hackiest so far. I also did not need Python 3.6. Though, I have not tested this extension yet to know how well it works.

**Comment by sepsol** [comment]
Same here.
